<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>CSharpIsNullAnalyzer</RootNamespace>
    <PackageId>CSharpIsNullAnalyzer</PackageId>
    <DevelopmentDependency>true</DevelopmentDependency>
    <Description>C# analyzer to encourage use of `is null` and `is object` syntax over `== null` or `!= null`.</Description>
    <PackageTags>C#;Analyzers</PackageTags>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);PackBuildOutputs</TargetsForTfmSpecificContentInPackage>
    <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
    <IncludeSymbols>false</IncludeSymbols>
    <GitVersionBaseDirectory>$(MSBuildProjectDirectory)</GitVersionBaseDirectory>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="build\**" Pack="true" PackagePath="build\" />
    <Content Include="tools\*.ps1" Pack="true" PackagePath="tools\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CSharpIsNullAnalyzer\CSharpIsNullAnalyzer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.ResxSourceGenerator" PrivateAssets="all" />
  </ItemGroup>

  <Target Name="PackBuildOutputs" DependsOnTargets="ResolveProjectReferences;SatelliteDllsProjectOutputGroup;SatelliteDllsProjectOutputGroupDependencies">
    <ItemGroup>
      <TfmSpecificPackageFile Include="$(TargetPath)" PackagePath="analyzers\dotnet\cs\" />
      <TfmSpecificPackageFile Include="@(SatelliteDllsProjectOutputGroupDependency)" PackagePath="analyzers\dotnet\cs\%(SatelliteDllsProjectOutputGroupDependency.DestinationSubDirectory)" Condition=" '%(SatelliteDllsProjectOutputGroupDependency.DestinationSubDirectory)' != '' " />
      <TfmSpecificPackageFile Include="@(SatelliteDllsProjectOutputGroupOutput->'%(FinalOutputPath)')" PackagePath="analyzers\dotnet\cs\%(SatelliteDllsProjectOutputGroupOutput.Culture)\" />
      <TfmSpecificPackageFile Include="%(_ResolvedProjectReferencePaths.Identity)" PackagePath="analyzers\dotnet\cs\" />
    </ItemGroup>
  </Target>
</Project>
