<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <TargetFrameworks Condition="'$(OS)' == 'Windows_NT'">$(TargetFrameworks);net472</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <RootNamespace />
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CSharpIsNullAnalyzer.CodeFixes\CSharpIsNullAnalyzer.CodeFixes.csproj" />
    <ProjectReference Include="..\..\src\CSharpIsNullAnalyzer\CSharpIsNullAnalyzer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.CodeFix.Testing" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" />
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>

</Project>
